version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - "54321:5432"
  web:
    build: .
    command: python ./main.py
    volumes:
      - .:/code
    env_file: .env
    depends_on:
      - db

volumes:
  db:
